### ISSUE TITLE
Delaying the update is broken if there is no cache yet

### ISSUE THREAD

**Issue by stof** [dunglas/php-socialshare#15]
In case there is no cache yet and delayed updates are enabled, it will return 0. Instead, it should perform the query in this case. Delaying the update makes sense for stale data, not for missing data.

**Comment by dunglas** [comment]
AFAIK in that case it will not return 0 but make the query: https://github.com/dunglas/php-socialshare/blob/master/src/SocialShare/SocialShare.php#L101

**Comment by dunglas** [comment]
My bad I misread the snippet. It's a real bug.

**Comment by dunglas** [comment]
And I finally remember the rationale behind that behavior:

The idea is retrieving shares must never slow down the navigation (it's a secondary information). Used with the `fastcgi_finish_request` function, this feature ensure that the page is always served fast and updates the number of shares **for the next visitor**. To work well, the page must have a relatively high traffic.

The current visitor will always receive an old result or 0 is it's the first request, but the page will always be served fast.

Having 0 has social media count for the first request is generally not a problem because:
* it's generally true when a post has just been published
* it's often the publisher or robot that will make the first request

If freshness/accuracy matter, the delay should not be used.
Other techniques such as retrieving the count in a periodic task can be used instead when performance is critical or the traffic is very low. It's just an helper features for small sites such as small blogs where doing asynchrone tasks are not possible or overkill.

Btw this behavior is explicitly documented in the blog post about Wordpress integration:

> Then, we create two helper functions to use in our theme’s templates: social_share_links that returns a share link and social_share_shares that returns the share counter. The last parameter of \SocialShare\SocialShare::getShares() function is set to true. This allows to delay the retrieving of share counts from social network when the \SocialShare\SocialShare::update() method will be called. If a value is already in the cache (how old it is doesn’t matter) it will be used, otherwise 0 will be returned.

Should be copied in README too.

**Comment by stof** [comment]
If it is the intended behavior, it should indeed be documented in this package (in the phpdoc of the method too)

**Comment by dunglas** [comment]
Fully agree. I'll do it.

**Comment by dunglas** [comment]
Fixed by d503adadae316d260cc0e3b5296192b3712b3406.
